import React, { Component } from "react";
//react-redux is the glue between react and redux
import { connect } from "react-redux";
import { selectBook } from "../actions/index";
//to make sure actions generated by actioncreators actually end up flowing through different reducers
import { bindActionCreators } from "redux";

class BookList extends Component {
  renderList() {
    return this.props.books.map(book => {
      return (
        <li
          key={book.title}
          onClick={() => this.props.selectBook(book)}
          className="list-group-item"
        >
          {book.title}
        </li>
      );
    });
  }
  render() {
    //console.log(this.props.asdf); // -> '123'
    return <ul className="list-group col-sm-4">{this.renderList()}</ul>;
  }
}

//whatever object retuned here will be available in component by this.props
//if the state changes this function will re-render
function mapStateToProps(state) {
  //whatever is returned will show up as props inside of booklist
  return {
    //asdf: "123"
    books: state.books
  };
}

//antrhing returned from this function will end up as props on the BookList container
function mapDispatchToProps(dispatch) {
  //whenever selectBook is called, the result should be passed to all of our reducers
  return bindActionCreators({ selectBook: selectBook }, dispatch);
  //After this function selectedBook will be avilable in props
}

//connect takes function and component and produces a container
//container is a component that is aware of the state that is contained by redux

//promote Booklist from a component to a container -
//it needs to know about this new dispatch method, selectBook. Make it available as a prop
export default connect(
  mapStateToProps,
  mapDispatchToProps
)(BookList);
